version: "3.8"

networks:
  app-network:

services:
  web:
    build:
      context: .
      dockerfile: Dockerfile.web.full
    ports:
      - 8081:80
    networks:
      - app-network
    depends_on:
      - db
  db:
    build:
      context: .
      dockerfile: Dockerfile.db.full
    networks:
      - app-network
    environment:
      MYSQL_ROOT_PASSWORD: "12345"
